[package]
name = "languageserver-types"
version = "0.11.1"
authors = ["Markus Westerlind <marwes91@gmail.com>", "Bruno Medeiros <bruno.do.medeiros@gmail.com>"]

description = "Types for interaction with a language server, using VSCode's Language Server Protocol"

repository = "https://github.com/gluon-lang/languageserver-types"
documentation = "https://docs.rs/languageserver-types"

readme = "README.md"

keywords = ["language", "server", "lsp", "vscode"]

license = "MIT"

[dependencies]
enum_primitive = "0.1.0"
serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"
url = "1.1.0"
url_serde = "0.2.0"
